# Generated by Django 5.2.8 on 2025-12-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_first_name_booking_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
